name: End-to-end tests
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./src
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Tests
        run: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.json
          install: false
          start: npm run start
          wait-on: 'http://localhost:3000'
